"""Initial migration.

Revision ID: d895624ced48
Revises: 
Create Date: 2024-09-30 19:07:23.902025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd895624ced48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('library_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('library_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.library_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('librarians',
    sa.Column('librarian_id', sa.Integer(), nullable=False),
    sa.Column('librarian_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.library_id'], ),
    sa.PrimaryKeyConstraint('librarian_id')
    )
    op.create_table('loans',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('librarian_loan_id', sa.Integer(), nullable=False),
    sa.Column('librarian_return_id', sa.Integer(), nullable=True),
    sa.Column('loan_timestamp', sa.DateTime(), nullable=False),
    sa.Column('return_timestamp', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['librarian_loan_id'], ['librarians.librarian_id'], ),
    sa.ForeignKeyConstraint(['librarian_return_id'], ['librarians.librarian_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_table('librarians')
    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('libraries')
    # ### end Alembic commands ###
